Dalmstar/face/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('star.urls')), 
]

Dalmstar/face/mysite/star/urls.py
from django.urls import path, include
from . import views
from star.views import classify_image
from .views import rank

app_name = 'star'

urlpatterns = [
    path('', classify_image, name='classify_image'),
    path('ranking/', rank, name='rank'),
    path('sub_menu_1/', views.sub_menu_1, name='sub_menu_1'), #3.35.235.162:8000/sub_menu_1로 가면 sub_menu_1함수로!
]

Dalmstar/face/mysite/star/models.py
import tensorflow as tf
from django.db import models
from PIL import Image
import numpy as np
import os

class ImageClassifier:
    def __init__(self, model_path):
        self.model = tf.keras.models.load_model(model_path)
    def classify_image(self, image):
        class_label=[   '강해린',
                        '김채원',
                        '뉴진스 하니',
                        '안유진',
                        '아린',
                        '장원영',
                        '카즈하',
                        '차은우',
                        '방탄소년단 뷔',
                        '정준하',
                        '정형돈',
                        '서강준',
                        '카리나',
                        '마동석',
                        '박보검',
                        '손석구',
                        '아이브 가을',
                        '이광수',
                        '침착맨',
                        '르세라핌 사쿠라',]
        img = Image.open(image)
        img = img.resize((224, 224))  # 모델에 맞는 이미지 크기로 조정
        img = np.array(img) / 255.0  # 이미지 정규화
        img = np.expand_dims(img, axis=0)  # 배치 차원 추가
        predictions = self.model.predict(img)
        pred_class = np.argmax(predictions, axis=1)
        class_index = np.argmax(predictions[0])  # 가장 높은 확률을 가진 클래스 인덱스
        confidence = predictions[0][class_index]  # 분류 확률
        result = class_label[pred_class[0]]
        result = {
            'class_label': result,
            'confidence': confidence,
        }
        return result

class Post(models.Model):
    confidence = models.FloatField()
    result = models.CharField(max_length=100)

    def __str__(self):
        return self.result

Dalmstar/face/mysite/star/forms.py
from django import forms
class ImageUploadForm(forms.Form):
    image = forms.ImageField()

Dalmstar/face/mysite/star/views.py
import os
from PIL import Image
from .models import Post
from django.shortcuts import render
from django.http import HttpResponse
from .forms import ImageUploadForm
from .models import ImageClassifier,Post
import numpy as np
import glob
model_path = 'star/team3_new.h5'  # 실제 모델 파일의 경로로 수정
            # 이미지 분류기 초기화
classifier = ImageClassifier(model_path)
def classify_image(request):

    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.cleaned_data['image']
            # 모델 경로 설정

            # 이미지 분류
            result = classifier.classify_image(image)
            Post.objects.create(confidence=result['confidence'], result=result['class_label'])
            return render(request, 'result.html', {'result': result})
    else:
        form = ImageUploadForm()
        
    return render(request, 'index.html', {'form': form})

def rank(request):
    results = Post.objects.all()
    return render(request, 'ranking.html', {'results': results})

def sub_menu_1(request):
    return render(request, 'sub_menu_1.html')

Dalmstar/face/mysite/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Stylish Portfolio - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico'%}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="resemble" style="background-image: url("/static/assets/img/bg-masthead.jpg");">
        <!-- Navigation-->
        <a class="menu-toggle rounded" href="#"><i class="fas fa-bars"></i></a>
        <nav id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <style>
                    .sub-menu {
                        display: none;
                    }
                    .sidebar-nav-item:hover .sub-menu {
                        display: block;
                    }
                </style>                
                <li class="sidebar-nav-item"><a href="{% url 'star:sub_menu_1' %}">About</a>
                </li>
                <li class="sidebar-nav-item"><a href="{% url 'star:classify_image' %}">닮은꼴 찾기</a></li>
            </ul>
        </nav>
        <!-- Header-->
        <header class="masthead d-flex align-items-center" style="background-image: url('/static/assets/img/bg-masthead.jpg');">
            <div class="container px-4 px-lg-5 text-center" style="background-image: url("..static/assets/img/bg-masthead.jpg");">
                <h1 class="mb-1">AWESOME 3조<br>Project Face</h1>
                <h3 class="mb-5"><em>"닮은꼴 찾기"</em></h3>
                <a class="btn btn-primary btn-xl" href="#about">시작</a>
            </div>
        </header>
        <!-- About-->
        <section class="content-section bg-light" id="about" style="background-color: transparent !important;">
            <div class="container px-4 px-lg-5 text-center" style="background-color: transparent;">
                <div class="row justify-content-center">
                    <div class="col-lg-10">
                        <h2>나의 닮은꼴은 무엇일까?</h2>
                        <p class="lead mb-5">
                            가보자아잇!
                        </p>
                    </div>
                </div>
            </div>
        </section>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>이미지 분류</title>
    <style>
        body {
            background-image: url("/static/assets/img/bg-masthead.jpg");
            background-size: cover;
        }

        .button-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            margin-top: 20px;
        }

        .button-container button {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <h5 style="text-align: center;"> ※ '.png' 파일은 안됩니다! ※</h5>
    <form method="POST" enctype="multipart/form-data" style="text-align: center;">
        <!-- 폼을 만들고 데이터를 서버로 보내는 형식이 post방식 사용, 
        인코딩 타입은 multipart/form-data 을 사용해서 브라우저가 이진파일 데이터를 적절하게 인코딩하여 서버로 보낼수 있도록 지정
         -->
        {% csrf_token %}
        {{ form }}
        <div class="button-container">
            <button type="submit" class="btn btn-primary btn-xl">이미지 분류하기</button>
        </div>
    </form>
</body>
</html>
<!-- profile.html -->
<!DOCTYPE html>
<html>
<head>
    <title>프로필</title>
    <style>
        .body {
            background-image: url("/static/assets/img/bg-masthead.jpg");
            background-repeat: no-repeat;
            background-size: cover;
        }
        .profile-container {
            text-align: center;
            margin-top: 50px;
        }
        .profile-image {
            width: 200px;
            height: 200px;
            border-radius: 50%;
        }
        .profile-name {
            font-size: 24px;
            margin-top: 20px;
        }
        .profile-description {
            margin-top: 10px;
        }
        .profile-title {
            text-align: center;
            margin-top: 50px;
            font-size: 32px;
            font-weight: bold;
        }

    </style>
</head>
<body>
    <div class="row">
        <div class="col">
            <h1 class="profile-title">팀 프로필</h1> <!-- 프로필 제목 추가 -->
            <div class="profile-container">
                <!-- 기존의 프로필 내용 유지 -->
            </div>
            <!-- 나머지 프로필 내용 유지 -->
        </div>
    </div>
    <div class="row">
        <div class="col">

            <div class="profile-container">
                <img class="profile-image" src="{% static 'KakaoTalk_Photo_2023-05-15-09-57-12.jpg' %}" alt="Profile Image">
                <h2 class="profile-name">규동누나</h2>
                <p class="profile-description">금쪽같은 내새끼</p>
            </div>
            <div class="profile-container">
                <img class="profile-image" src="{% static 'KakaoTalk_Photo_2023-05-15-16-04-51.jpg' %}" alt="Profile Image">
                <h2 class="profile-name">의사소통이 능한 자</h2>
                <p class="profile-description">듣고 싶은 말만 들음</p>
            </div>
            <div class="profile-container">
                <img class="profile-image" src="{% static 'KakaoTalk_Photo_2023-05-15-15-17-02.jpg' %}" alt="Profile Image">
                <h2 class="profile-name">문광식(29세)</h2>
                <p class="profile-description">이 아이가 배고픔을 알까요?</p>
            </div>
        </div>
        <div class="col">
            <div class="profile-container">
                <img class="profile-image" src="{% static 'IMG_5173.jpg' %}" alt="Profile Image">
                <h2 class="profile-name">리밥풀</h2>
                <p class="profile-description">국밥급 든든함</p>    
            </div>
            <div class="profile-container">
                <img class="profile-image" src="{% static 'IMG_5140.jpg' %}" alt="Profile Image">
                <h2 class="profile-name">사랑의렉카꾼</h2>
                <p class="profile-description">여자친구의 존재가 곧 나의 존재</p>
            </div>
            <div class="profile-container">
                <img class="profile-image" src="{% static 'IMG_6808.jpg' %}" alt="Profile Image">
                <h2 class="profile-name">성시경 닮은꼴</h2>
                <p class="profile-description">잘자요~</p>
            </div>
        </div>
    </div>
</body>     
</html>

<!-- Footer-->
<footer class="footer text-center">
    <div class="container px-4 px-lg-5">
        <ul class="list-inline mb-5">
            <li class="list-inline-item">
                <a class="social-link rounded-circle text-white mr-3" href="#!"><i class="icon-social-facebook"></i></a>
            </li>
            <li class="list-inline-item">
                <a class="social-link rounded-circle text-white mr-3" href="#!"><i class="icon-social-twitter"></i></a>
            </li>
            <li class="list-inline-item">
                <a class="social-link rounded-circle text-white" href="#!"><i class="icon-social-github"></i></a>
            </li>
        </ul>
        <p class="text-muted small mb-0">Copyright &copy; Your Website 2023</p>
    </div>
</footer>
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top"><i class="fas fa-angle-up"></i></a>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js'%}"></script>
</body>
</html>

Dalmstar/face/mysite/templates/ranking.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>결과 목록</title>
</head>
<body>
    <h1>결과 목록</h1>
    <ul>
        {% for result in results %}
            <li>{{ result.confidence }}</li>
        {% endfor %}
    </ul>
</body>
</html>

Dalmstar/face/mysite/templates/result.html
<!-- result.html -->
{%load static%}
<!DOCTYPE html>
<html>
<header>
	<meta charset="UTF-8">
	<title>분류 결과</title>
	<style>
		body {
			display: flex;
			flex-direction: column;
			justify-content: top center;
			align-items: center;
			height: 100vh;
			text-align: center;
		}
		.return-button {
			display: inline-block;
			padding: 10px 20px;
			background-color: #006242;
			color: white;
			text-decoration: none;
			border-radius: 5px;
			font-size: 16px;
			margin-top: 20px;
		}

		.return-button:hover {
			background-color: #4CAF50;
		}

		.profile-image {
            width: 400px; /* 원하는 너비로 조정 */
            height: auto; /* 너비에 맞춰 자동으로 높이 조정 */
        }
		</style>
	</style>
	
</header>

<body>
   

    <h1>분류 결과</h1>
    <p>예측 결과: 대박 미친 {{ result.class_label }} 입니다...</p>
    <img class="profile-image" src="{% static result.class_label|add:'.jpg' %}">

    <p><a href="{% url 'star:classify_image' %}" class="return-button">돌아가기</a></p>
</body>

Dalmstar/face/mysite/templates/sub_menu_1.html
<!-- sub_menu_1.html -->
<!DOCTYPE html>
<html>
<head>
    <title>아이템 선정</title>
    <!-- 필요한 스타일시트 및 스크립트 태그를 추가하세요 -->
    <style>
         body {
            background-image: url('/static/assets/img/bg-masthead.jpg');
            /* background-repeat: no-repeat; */
            background-size: cover;
        }
        .center-text {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            text-align: center;
            height: 100vh;
        }
        .container h1 {
            font-size: 48px;
            /* 화면 전체 높이에 맞게 조절 */
        }
        .header-container {
            text-align: center;
            margin-top: 50px;
        }
        .split-container {
            display: flex;
            justify-content: center;
            border-top: 1px solid black;
            flex-wrap: wrap;
            position: relative;
        }
        .split-container::before {
            content: "";
            width: 1px;
            background-color: black; /* 세로줄 색상 */
            position: absolute; /* 절대적 위치 설정 */
            top: 240px; /* 세로줄이 가로줄 위에 위치하도록 설정 */
            bottom: -400px; /* 세로줄이 가장 아래까지 표시되도록 설정 */
            left: 50%; /* 가운데로 위치하도록 설정 */
            transform: translateY(-50%); /* 세로줄을 정중앙에 위치시키도록 설정 */
            margin-top: 50px; /* 상단 여백 조정 */
        }
        .split-container .col {
            flex: 1;
            padding: 20px;
        }
        body, html {
            height: 100%;
            margin: 0;
            display: flex;
            flex-direction: column;
        }
        .content {
            flex: 1;
        }
    </style>
    
    
</head>

<body>
    <div class="header-container">
        <h1 >프로젝트 Face</h1>
        <h3 class="mb-5"><em>딥러닝을 이용하여 학습시킨 모델을 활용하여<br>닮은 유명인을 찾아주는 홈페이지 만들기</em></h3>
    </div>
    <div class="split-container">
        <div class="col" style="background-color: white;">
            <h2 style="text-align: center;">프로젝트명칭: Face</h2>
            <p>개발 인원: 6명</p>
            <p>개발 기간: 2023.05.12 - 2023.05.18</p>
            <p>간단한 소개: 딥러닝을 이용하여 학습시킨 모델을 홈페이지에 적용하여 사용자들이 사진을 올리면 닮은 연예인을<br>        보여주도록 함</p>
            <p>개발 언어: python</p>
            <p>형상 관리 틀: GitHub</p>
            <p>데이터베이스: SQLite</p>
            
        </div>
            <!-- 왼쪽 내용 -->
        <div class="col">
            <h2 style="text-align: center;">DB 설계</h2>
            <img src="/static/DB.jpg" alt="DB 설계 이미지" width="700">
        </div>
    </div>
</body>

</html>